CS
  ::= Expr* EOF

Expr
  ::=   (  var Operator ( literal | URI )
         | items ( Operator items (Operator items )* )? ) Separator?

var ::= "$"nstring

items ::= item ("," item)?

item ::= URI | segment | literal

Separator
  ::= ';'

literal ::= '"' astring '"'

URI
  ::= "[" (scheme hostport?)? path  "]"

hostport
  ::= host (":" port)?

host
  ::= nstring

port
  ::= digit*

path
  ::= (segment)*

segment
  ::= ('/'|'.') string

comments ::= "#" astring (astring)?

whitespace
         ::=  S^WS | comments
          /* ws: definition */

<?TOKENS?>

scheme
  ::= ("https" | "http" | "file") '://'

Operator
  ::= '|' |  '=' | '>>' | '>' | '!' | '?' | "!=" | "=="

nstring ::= alpha (alpha | schar | digit)*

string ::= character*

astring ::= all*

character ::= alpha | digit | schar

all ::= Operator | alpha | digit | schar

schar ::= "_" | "."

digit ::= [0-9]

alpha ::= [a-z] | [A-Z]

S        ::= ( #x0020 | #x0009 | #x000D | #x000A )+

EOF      ::= $
