CS
  ::= Expr* EOF

Expr
  ::= ( opt | items ( Operator items (Operator items )* )? ) Separator?

opt ::= "set" nstring "=" ( literal | URI )

items ::= item ("," item)?

item ::= URI | var | segment | literal

Operator
  ::= '|' |  '=' | '>>' | '>' | '!' | '?' | "!=" | "=="

Separator
  ::= ';'

literal ::= '"' all* '"'

var
  ::= "$" nstring

URI
  ::= "[" (scheme hostport?)? path  "]"

scheme
  ::= ("https" | "http" | "file") '://'

hostport
  ::= host (":" port)?

host
  ::= nstring

port
  ::= digit*

path
  ::= (segment)*

segment
  ::= '/' string

nstring ::= alpha (alpha | schar | digit)*

string ::= character*

character ::= alpha | digit | schar

all ::= Operator | alpha | digit | schar

whitespace
         ::=  S^WS
          /* ws: definition */

<?TOKENS?>

schar ::= "_" | "."

digit ::= [0-9]

alpha ::= [a-z] | [A-Z]

S        ::= ( #x0020 | #x0009 | #x000D | #x000A )+

EOF      ::= $
