CS
  ::= Exprs EOF

Exprs
  ::= (Expr)*

Expr
  ::= (URI) Operator (URI) Separator?

Operator
  ::= ("|" | ">" )

Separator
  ::= ';'

URI
  ::=  scheme authority? host? port? path query? fragment?

scheme
  ::= string '://'

authority
  ::= user (':' pass)? '@'

user
  ::= string

pass
  ::= string

host
  ::= string

port
  ::= ":" IntegerLiteral

path
  ::= segment*

segment
  ::= '/' string

query
  ::= '?'

fragment
  ::= '#' string?

Whitespace
         ::= S^WS
          /* ws: definition */

<?TOKENS?>

IntegerLiteral
         ::= Digits

Digits   ::= [0-9]+

S        ::= ( #x0020 | #x0009 | #x000D | #x000A )+

string   ::= ( Char )*

Char     ::= '.' | letter

letter ::= "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z"

digit ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

EOF      ::= $
